version: '2.0'

services: 
    db:
      image: mysql:8.0.3
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: example
      ports:
        - "3306:3306"  

    adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080" 
        
    server:
      image:        openjdk:8
      environment:
        add:         target/useraccount.jar  useraccount.jar  
        expose:      8081
        entrypoint:  ["java","-jar","useraccount.jar"]

        
      